openapi: 3.2.0
info:
  title: OneAtlas Basemap Get Capabilities API
  description: OneAtlas Basemap API is a geospatial service that provides access to high-resolution satellite imagery and basemaps.
  version: '2.0'
servers:
- url: https://view-bm.api.oneatlas.airbus.com
tags:
- name: Get Capabilities
paths:
  /basemap/wmts?SERVICE=WMTS&REQUEST=GetCapabilities:
    get:
      summary: Service Capabilities
      description: Allows authorized users to see the capacities of the service.
      security:
      - Bearer: []
      responses:
        '200':
          description: Request successful
        '401':
          description: 'Unauthorized: the authorization is missing or has expired.'
      tags:
      - Get Capabilities
      operationId: getBasemapWmts?SERVICE=WMTS&REQUEST=GetCapabilities
      x-operation-id-source: derived
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: 'Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".'
