openapi: 3.2.0
info:
  contact:
    email: intelligence-customertechnicalsupport@fr.airbus.com
    name: API support
    url: https://oneatlas.airbus.com
  title: OneAtlas Data Living Library Health API
  description: OneAtlas Data Living Library is a platform that provides users with access to a diverse range of geospatial data and satellite imagery.
servers:
- description: API server
  url: https://data.api.oneatlas.airbus.com
tags:
- name: Health
paths:
  /api/v1/health:
    get:
      description: Health check route
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  status:
                    pattern: ok
                type: object
          description: API status
      summary: Health Check
      tags:
      - Health
      operationId: getApiV1Health
      x-operation-id-source: derived
x-tagGroups:
- name: Authentication
  tags:
  - APIkey management
  - Token retrieval
- name: Catalog search
  tags:
  - Catalog search
- name: Living Library ordering
  tags:
  - Orders
  - Subscriptions
