openapi: 3.0.3
info:
  title: OneAtlas WorldDEM Access Get Capabilities API
  version: 1.0.1
  contact:
    email: dl-geo-webservices@airbus.com
  description: The OneAtlas WorldDEM API is a tool that provides access to high-resolution global elevation data. This data, collected by satellites and processed using advanced technologies, offers a detailed and accurate representation of the Earth's surface. By integrating the WorldDEM API into their applications, users can benefit from precise terrain information for a wide range of use cases, such as urban planning, disaster response, agriculture, and infrastructure development. This API allows developers to easily incorporate elevation data into their projects, enabling them to create more accurate and effective solutions.
servers:
- url: https://sar.api.oneatlas.airbus.com/v1
  description: OneAtlas - Elevation
security:
- basicAuth: []
tags:
- name: Get Capabilities
paths:
  /basemap/wmts?SERVICE=WMTS&REQUEST=GetCapabilities:
    get:
      summary: Service Capabilities.
      description: Allows authorized users to see the capacities of the service.
      security:
      - Bearer: []
      responses:
        '200':
          description: Request successful
        '401':
          description: 'Unauthorized: the authorization is missing or has expired.'
      tags:
      - Get Capabilities
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
